#
# Try to find Cinder library and include path.
# Once done this will define
#
# CINDER_FOUND
# CINDER_INCLUDE_PATH
# CINDER_LIBRARY
# 

FIND_PATH( CINDER_INCLUDE_PATH Cinder.h
  PATHS
$ENV{CINDER_ROOT}
DOC "The directory where cinder.h resides")

FIND_LIBRARY( CINDER_LIBRARY Cinder
    PATHS
    $ENV{CINDER_ROOT}
    DOC "The Cinder library")

SET(CINDER_FOUND "NO")
IF (CINDER_INCLUDE_PATH AND CINDER_LIBRARY)
  SET(CINDER_FOUND "YES")
ENDIF (CINDER_INCLUDE_PATH AND CINDER_LIBRARY)

INCLUDE(${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Cinder DEFAULT_MSG CINDER_INCLUDE_PATH CINDER_LIBRARY)